### ISSUE TITLE
`InstallDependency` fills up disk on Windows2012R2

### ISSUE THREAD

**Issue by sesmith177** [cloudfoundry/libbuildpack#13]
`InstallDependency` creates a temp directory to fetch the dependency to here: https://github.com/cloudfoundry/libbuildpack/blob/e118861edfe5558db89cc012af26d315bc86279d/installer.go#L33

but never explicitly cleans it up.

On Windows2012R2, the temp directory ends up in the system temp directory `c:\windows\temp`. Since this is outside the "container" filesystem, it is not deleted when the "container" is deleted. Over time, these will lead to the disk filling up, taking down the cell

**Comment by Zanadar** [comment]
Done
