### ISSUE TITLE
Update CF CLI

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/libbuildpack#145]
This library (specifically cutlass) assumes the CF CLI is v6. v6 is now deprecated, and so we should upgrade to v7.

In addition to using a supported version of the CF CLI, this will enable us (and any consumers) to use newer CF CLI features.

See also https://github.com/cloudfoundry/buildpacks-ci/issues/88

**Comment by ryanmoran** [comment]
Closing as low-priority tech debt.
