### ISSUE TITLE
Cutlass: Better error output

### ISSUE THREAD

**Issue by menehune23** [cloudfoundry/libbuildpack#146]
When deploying an app with `App.Push()` or similar, helpful output (i.e. stdout, stderr) is lost when returning an error.

We should adjust these commands to include this output in the error, similar to [this](https://github.com/cloudfoundry/libbuildpack/blob/master/cutlass/cf.go#L396).

**Comment by ryanmoran** [comment]
Closing as the team has chosen to move all test suites to switchblade which has better logging output already.
