### ISSUE TITLE
buildpack-packager doesn't handle file URIs

### ISSUE THREAD

**Issue by sesmith177** [cloudfoundry/libbuildpack#2]
While working on changes to the hwc.exe included in the HWC buildpack, we noticed that buildpack packager no longer handled file URIs in `manifest.yml`, e.g. `file:///path/to/dev/hwc.zip`. This appears to be a regression from the old Ruby gem. 

We were able to use 9e6a725c74681d78531b70091aca7e3c1faac054 to work around this issue

**Comment by sclevine** [comment]
Closing, as I think this is fixed by https://github.com/cloudfoundry/libbuildpack/commit/9e6a725c74681d78531b70091aca7e3c1faac054
