### ISSUE TITLE
CreateOrUpdateBuildpack race condition

### ISSUE THREAD

**Issue by jimmykarily** [cloudfoundry/libbuildpack#21]
We are facing the following issue with BRATs. The [CreateOrUpdateBuildpack](https://github.com/cloudfoundry/libbuildpack/blob/master/cutlass/cf.go#L178) function fails when calling UpdateBuildpack with the following error:

```
  Expected error:
	
      <*errors.errorString | 0xc420202140>: {
	
          s: "Failed to create or update buildpack: Failed to update buildpack by running 'cf update-buildpack brats_go_cached_ooqung_buildpack -p /tmp/build/73b56eb0/git.buildpack/go_buildpack-cached-sle12-vooqung.zip --enable -s sle12':\nFAILED\nBuildpack brats_go_cached_ooqung_buildpack not found\n\nexit status 1",
	
      }
	
      Failed to create or update buildpack: Failed to update buildpack by running 'cf update-buildpack brats_go_cached_ooqung_buildpack -p /tmp/build/73b56eb0/git.buildpack/go_buildpack-cached-sle12-vooqung.zip --enable -s sle12':
	
      FAILED
	
      Buildpack brats_go_cached_ooqung_buildpack not found
	
      
	
      exit status 1
	
  not to have occurred
```

The function first calls CreateBuildpack and would not call UpdateBuildpack if the first one failed. That means, although the Create command succeeds, the buildpack is not there immediately. To debug the issue, we added a `cf buildpacks` command between the `CreateBuildpack` and the `UpdateBuildpack`. This command takes a couple of seconds and surprisingly makes the tests succeed.

It seems that there is a window between `cf create-buildpack` and until the buildpack is "visible" everywhere inside cf. This only happens with our Go buildpack which is the biggest among the ones we tried (~900Mb).

If there is something that needs to happen before `cf update-buildpack` can be called, then we should add a command that checks if the buildpack is there and maybe retry a couple of times with some sleeping period.

If this makes sense, I can create a PR.

**Comment by ameyer-pivotal** [comment]
@jimmykarily Thanks for catching and debugging this. It definitely sounds like a check for the existence of the buildpack (perhaps by calling `cf buildpacks` and parsing the result) could be of benefit. We'd for sure welcome a PR.

**Comment by jimmykarily** [comment]
Here it is: https://github.com/cloudfoundry/libbuildpack/pull/22

**Comment by jimmykarily** [comment]
@tylerphelan suggested something on the linked PR which might explain why this happens. Need to check. Closing this for now.
