### ISSUE TITLE
Request: buildpack-packager init -supply

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/libbuildpack#28]
My guess is that most new buildpacks created from this point onwards will be Supply buildpacks. Currently `buildpack-packager init` assumes you want a normal buildpack and generates all the `bin/` and `src/` files.

A suppy buildpack can be much simpler and easier for a new developer to grok.

Either:

* `init` should assume a supply buildpack and offer an `init -full` flag; or
* support an `init -supply` flag for a supply buildpack

This feature would probably require a rewrite of the scaffold system and the upgrade system.

**Comment by Zanadar** [comment]
@drnic We'll look into how this fits out priorities. Thanks for the issue.

**Comment by drnic** [comment]
I’ll close this issue/ idea. I can see from v3 work that this repo wont have too many future users despite my riveting new blog series :)
