### ISSUE TITLE
Bump `buildpack-packager init` bindata in CI please

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/libbuildpack#33]
When I install this repo, the `buildpack-packager init` scaffold generator is creating an `install_go.sh` that installs go1.10; not go1.12, which is in the latest scaffold script.

I think the bindata.go + cfbindata.go files are no being recreated when scaffold files are changed. Could this be done in CI please? Or would you just like scaffold PRs to also bump the bindata files?

https://github.com/cloudfoundry/libbuildpack/tree/master/packager - `bindata.go` is 6 mths old, `cfbindata.go` is over a year old.

*Update:* I see in readme that it discusses scaffold updates in PRs, but perhaps since multiple open PRs currently all modify scaffold it isn't possible for PRs to include bindata generated?

**Comment by ryanmoran** [comment]
We aren't going to spend the time to have this automatically updated in CI as we are moving away from this tooling in the medium-term. I've gone ahead and manually bumped the version of Go in the scaffold to 1.13.5 which should be the latest version as of this comment. Thanks!
