### ISSUE TITLE
Installing the buildpack-packager tool is broken 

### ISSUE THREAD

**Issue by vbakayov** [cloudfoundry/libbuildpack#39]
Hi Team,

The installation script of the buildpack-packager is failing with the below error. Therefore, we can't build the buildpack-packager tool. 

`cannot use depVersion (type "github.com/Masterminds/semver".Version) as type *"github.com/Masterminds/semver".Version in append`
`cannot convert depVersions (type []*"github.com/Masterminds/semver".Version) to type "github.com/Masterminds/semver".Collection`

How to reproduce? 
 execute 
`go get -v github.com/cloudfoundry/libbuildpack/packager/buildpack-packager`

**Comment by Zanadar** [comment]
Works for me:
```
± zm |develop ✓| → go get -v github.com/cloudfoundry/libbuildpack/packager/buildpack-packager
github.com/cloudfoundry/libbuildpack (download)
github.com/Masterminds/semver (download)
github.com/blang/semver (download)
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/google/subcommands (download)
github.com/google/subcommands
github.com/Masterminds/semver
github.com/blang/semver
gopkg.in/yaml.v2
github.com/cloudfoundry/libbuildpack
github.com/cloudfoundry/libbuildpack/packager
github.com/cloudfoundry/libbuildpack/packager/buildpack-packager
```

probably need to clean your modcache or upgrade your version of go or something like that.
