### ISSUE TITLE
BRATs credential redaction and CloudFront/S3

### ISSUE THREAD

**Issue by jimmykarily** [cloudfoundry/libbuildpack#8]
BRATs that test the "redaction" of credentials in the staging output are arbitrarily changing requests adding credentials to them (https://github.com/cloudfoundry/libbuildpack/blob/master/bratshelper/tests.go#L180).
Although no credentials are required, CloudFront seems to have no problem to serve the requested file (ignoring the credentials).

This is not the case for S3 (without CloudFront) which returns an error. This makes the relevant BRATs to fail.

These tests only test the redaction of credentials so the actual url is not relevant. A solution would be to also manipulate the actual url and always point
to a url that will not complain if credentials are supplied.

To reproduce the issue compair these two:

Upstream dependency which works:

```
curl https://login:passworasdfd@buildpacks.cloudfoundry.org/dependencies/httpd/httpd-2.4.29-linux-x64-689e1bd2.tgz --output deleteme && cat deleteme && rm deleteme
```

Our dependency which doesn't work:

```
curl https://login:passworasdfd@s3.amazonaws.com/cf-opensusefs2/dependencies/httpd/httpd-2.4.29-linux-x64-638a797d.tgz --output deleteme && cat deleteme && rm deleteme
```

Our workaround for the old (external) BRATs was to stub those test to use cflinuxfs2 stack in order to use the upstream uris. Besides being a hack, choosing a stack in not supported in internal BRATs, at least yet.

We can prepare a Pull Request that stubs the url to some known-to-work url if you find this a good solution.

**Comment by sclevine** [comment]
@dgodd

**Comment by dgodd** [comment]
@jimmykarily Assuming I understand the problem correctly, I think the correct answer is to not change urls which already contain username/password in them and instead assert that those aren't in the output. I will have a look at that.

**Comment by dgodd** [comment]
@jimmykarily I just re-read your request, and realised I misunderstood. Yes, I am happy to receive a PR which rewrites the s3 buckets to something else.

**Comment by sclevine** [comment]
Happy to accept a PR for this, but closing this issue for now due to inactivity.
